[target.'cfg(all())']
rustflags = [
	"-Aclippy::assertions_on_constants",
	"-Aclippy::empty_enum",
	"-Aclippy::enum_clike_unportable_variant",
	"-Aclippy::enum_glob_use",
	"-Aclippy::expect_fun_call",
	"-Dtext_direction_codepoint_in_comment",
	"-Dtext_direction_codepoint_in_literal",
	"-Wclippy::as_conversions",
	"-Wclippy::assertions_on_result_states",
	"-Wclippy::await_holding_lock",
	"-Wclippy::await_holding_refcell_ref",
	"-Wclippy::bind_instead_of_map",
	"-Wclippy::blocks_in_if_conditions",
	"-Wclippy::bool_to_int_with_if",
	"-Wclippy::borrow_as_ptr",
	"-Wclippy::borrow_deref_ref",
	"-Wclippy::borrowed_box",
	"-Wclippy::box_default",
	"-Wclippy::bytes_count_to_len",
	"-Wclippy::bytes_nth",
	"-Wclippy::cast_abs_to_unsigned",
	"-Wclippy::cast_lossless",
	"-Wclippy::cast_lossless",
	"-Wclippy::cast_possible_truncation",
	"-Wclippy::cast_possible_wrap",
	"-Wclippy::cast_precision_loss",
	"-Wclippy::cast_precision_loss",
	"-Wclippy::cast_sign_loss",
	"-Wclippy::cast_slice_different_sizes",
	"-Wclippy::cast_slice_from_raw_parts",
	"-Wclippy::char_lit_as_u8",
	"-Wclippy::checked_conversions",
	"-Wclippy::clone_on_copy",
	"-Wclippy::cloned_instead_of_copied",
	"-Wclippy::collapsible_if",
	"-Wclippy::collapsible_str_replace",
	"-Wclippy::crate_in_macro_def",
	"-Wclippy::dbg_macro",
	"-Wclippy::dbg_macro",
	"-Wclippy::default_instead_of_iter_empty",
	"-Wclippy::default_numeric_fallback",
	"-Wclippy::derivable_impls",
	"-Wclippy::disallowed_methods", 
	"-Wclippy::disallowed_script_idents", 
	"-Wclippy::disallowed_types",
	"-Wclippy::empty_enum",
	"-Wclippy::enum_glob_use",
	"-Wclippy::equatable_if_let",
	"-Wclippy::err_expect",
	"-Wclippy::exhaustive_enums",
	"-Wclippy::exhaustive_structs",
	"-Wclippy::expect_fun_call",
	"-Wclippy::expect_used",
	"-Wclippy::explicit_into_iter_loop",
	"-Wclippy::explicit_iter_loop",
	"-Wclippy::explicit_write",
	"-Wclippy::extend_with_drain",
	"-Wclippy::filter_map_identity",
	"-Wclippy::filter_map_next",
	"-Wclippy::filter_next",
	"-Wclippy::flat_map_identity",
	"-Wclippy::flat_map_option",
	"-Wclippy::float_arithmetic", 
	"-Wclippy::float_cmp", 
	"-Wclippy::float_cmp_const",
	"-Wclippy::fn_params_excessive_bools",
	"-Wclippy::from_over_into",
	"-Wclippy::from_str_radix_10",
	"-Wclippy::get_last_with_len",
	"-Wclippy::get_unwrap",
	"-Wclippy::implicit_clone",
	"-Wclippy::implicit_saturating_add",
	"-Wclippy::implicit_saturating_sub",
	"-Wclippy::imprecise_flops", 
	"-Wclippy::inconsistent_struct_constructor",
	"-Wclippy::inefficient_to_string",
	"-Wclippy::inefficient_to_string",
	"-Wclippy::infallible_destructuring_match",
	"-Wclippy::init_numbered_fields",
	"-Wclippy::inline_always",
	"-Wclippy::inline_fn_without_body",
	"-Wclippy::int_plus_one",
	"-Wclippy::integer_arithmetic",
	"-Wclippy::into_iter_on_ref",
	"-Wclippy::is_digit_ascii_radix",
	"-Wclippy::iter_cloned_collect",
	"-Wclippy::iter_count",
	"-Wclippy::iter_kv_map",
	"-Wclippy::iter_next_slice",
	"-Wclippy::iter_nth_zero",
	"-Wclippy::iter_overeager_cloned",
	"-Wclippy::iter_skip_next",
	"-Wclippy::large_const_arrays",
	"-Wclippy::large_stack_arrays",
	"-Wclippy::large_types_passed_by_value",
	"-Wclippy::len_zero",
	"-Wclippy::let_unit_value",
	"-Wclippy::manual_assert",
	"-Wclippy::manual_async_fn",
	"-Wclippy::manual_bits",
	"-Wclippy::manual_find",
	"-Wclippy::manual_is_ascii_check",
	"-Wclippy::manual_let_else",
	"-Wclippy::manual_ok_or",
	"-Wclippy::manual_rem_euclid",
	"-Wclippy::manual_retain",
	"-Wclippy::manual_saturating_arithmetic",
	"-Wclippy::manual_str_repeat",
	"-Wclippy::manual_string_new",
	"-Wclippy::manual_unwrap_or",
	"-Wclippy::map_clone",
	"-Wclippy::map_collect_result_unit",
	"-Wclippy::map_flatten",
	"-Wclippy::map_identity",
	"-Wclippy::map_unwrap_or",
	"-Wclippy::map_unwrap_or",
	"-Wclippy::match_as_ref",
	"-Wclippy::match_bool",
	"-Wclippy::match_bool",
	"-Wclippy::match_result_ok",
	"-Wclippy::match_single_binding",
	"-Wclippy::match_str_case_mismatch",
	"-Wclippy::missing_errors_doc",
	"-Wclippy::missing_panics_doc",
	"-Wclippy::missing_spin_loop",
	"-Wclippy::mod_module_files",
	"-Wclippy::modulo_arithmetic",
	"-Wclippy::needless_arbitrary_self_type",
	"-Wclippy::needless_bitwise_bool",
	"-Wclippy::needless_bool",
	"-Wclippy::needless_collect",
	"-Wclippy::needless_late_init",
	"-Wclippy::needless_match",
	"-Wclippy::needless_option_as_deref",
	"-Wclippy::needless_option_take",
	"-Wclippy::needless_parens_on_range_literals",
	"-Wclippy::needless_question_mark",
	"-Wclippy::neg_multiply",
	"-Wclippy::no_effect",
	"-Wclippy::non_octal_unix_permissions",
	"-Wclippy::nonstandard_macro_braces",
	"-Wclippy::obfuscated_if_else",
	"-Wclippy::option_as_ref_deref",
	"-Wclippy::option_map_or_none",
	"-Wclippy::or_fun_call",
	"-Wclippy::or_then_unwrap",
	"-Wclippy::partialeq_to_none",
	"-Wclippy::path_buf_push_overwrite",
	"-Wclippy::precedence",
	"-Wclippy::ptr_as_ptr",
	"-Wclippy::ptr_as_ptr",
	"-Wclippy::ptr_offset_with_cast",
	"-Wclippy::question_mark",
	"-Wclippy::rc_clone_in_vec_init",
	"-Wclippy::redundant_clone",
	"-Wclippy::redundant_closure_call",
	"-Wclippy::redundant_field_names",
	"-Wclippy::redundant_pattern",
	"-Wclippy::redundant_pub_crate",
	"-Wclippy::redundant_slicing",
	"-Wclippy::redundant_static_lifetimes",
	"-Wclippy::repeat_once",
	"-Wclippy::search_is_some",
	"-Wclippy::seek_from_current",
	"-Wclippy::seek_to_start_instead_of_rewind",
	"-Wclippy::self_named_module_files", 
	"-Wclippy::single_char_pattern",
	"-Wclippy::single_component_path_imports",
	"-Wclippy::single_element_loop",
	"-Wclippy::single_match",
	"-Wclippy::stable_sort_primitive",
	"-Wclippy::strlen_on_c_strings",
	"-Wclippy::struct_excessive_bools",
	"-Wclippy::suboptimal_flops",
	"-Wclippy::suspicious_operation_groupings",
	"-Wclippy::swap_ptr_to_ref",
	"-Wclippy::to_digit_is_some",
	"-Wclippy::transmute_ptr_to_ref",
	"-Wclippy::transmutes_expressible_as_ptr_casts",
	"-Wclippy::trivially_copy_pass_by_ref",
	"-Wclippy::try_err",
	"-Wclippy::unit_arg",
	"-Wclippy::unnecessary_cast",
	"-Wclippy::unnecessary_fold",
	"-Wclippy::unnecessary_join",
	"-Wclippy::unnecessary_owned_empty_strings",
	"-Wclippy::unnecessary_sort_by",
	"-Wclippy::unnecessary_to_owned",
	"-Wclippy::unneeded_wildcard_pattern",
	"-Wclippy::unnested_or_patterns",
	"-Wclippy::unused_rounding",
	"-Wclippy::unused_unit",
	"-Wclippy::unwrap_or_else_default",
	"-Wclippy::unwrap_used",
	"-Wclippy::use_self",
	"-Wclippy::useless_asref",
	"-Wclippy::vec_box",
	"-Wclippy::vec_init_then_push",
	"-Wclippy::while_let_loop",
	"-Wclippy::while_let_on_iterator",
	"-Wclippy::wildcard_imports",
	"-Wclippy::wildcard_imports",
	# "-Wclippy::needless_for_each",
]
